# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llama_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'llama_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13llama_service.proto\x12\rllama_service\"\x1e\n\x0eMessageRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"#\n\x0fMessageResponse\x12\x10\n\x08response\x18\x01 \x01(\t2a\n\x0cLlamaService\x12Q\n\x0eProcessMessage\x12\x1d.llama_service.MessageRequest\x1a\x1e.llama_service.MessageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llama_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=38
  _globals['_MESSAGEREQUEST']._serialized_end=68
  _globals['_MESSAGERESPONSE']._serialized_start=70
  _globals['_MESSAGERESPONSE']._serialized_end=105
  _globals['_LLAMASERVICE']._serialized_start=107
  _globals['_LLAMASERVICE']._serialized_end=204
# @@protoc_insertion_point(module_scope)
